//custom data type definitions
export type ProductType = {
  productId: number;
  productName: string;
  productStock: number;
  productImage: string;
  productSalePrice: number;
  productPrice: number;
};

// Generated by https://quicktype.io

export interface UserType {
  localId: string;
  email: string;
  displayName: string;
  idToken: string;
  registered: boolean;
  refreshToken: string;
  expiresIn: string;
}
